apiVersion: v1
kind: Service
metadata:
  name: e-commerce-db-service

spec:
  ports:
    - port: 3306
  selector:
    app: e-commerce-db
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: e-commerce-db-svc

spec:
  ports:
    - port: 3306
  selector:
    app: e-commerce-db
