apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: e-commerce-db
  labels:
    app: e-commerce-db
spec:
  replicas: 1
  serviceName: e-commerce-db-hsvc
  selector:
    matchLabels:
      app: e-commerce-db
  template:
    metadata:
      name: e-commerce-db
      labels:
        app: e-commerce-db
    spec: 
      containers:
        - name: e-commerce-db
          image: pawanitzone/e-commerce-db
          ports:
            - containerPort: 3306
          env:
           - name: MYSQL_ALLOW_EMPTY_PASSWORD
               value: "1"
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: e-commerce-vol
              subPath: mysql
          livenessProbe:
            exec:
              command: ["mysqladmin", "ping"]
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5

      volumes:
        - name: e-commerce-vol
          persistentVolumeClaim:
            claimName: e-commerce-pvc-claim
