apiVersion: v1
kind: Service
metadata:
  name: e-commerce
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      #nodePort: 31380
      protocol: TCP
  selector:
     app: e-commerce